CREATE DATABASE "my_cloud";

CREATE USER my_cloud WITH PASSWORD '';

GRANT CONNECT ON DATABASE "my_cloud" TO my_cloud;

GRANT USAGE ON SCHEMA public TO my_cloud;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO my_cloud;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO my_cloud;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO my_cloud;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT ON SEQUENCES TO my_cloud;